# App configs
spring.application.name=finance_advisor
server.port=8081

# plaid configs
plaid.client-id=680d7b8f7e28700022c1458e
plaid.secret=2b363e616a3c55fd8c42502c287e61
plaid.environment=sandbox


# postgres configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/fin_advisor
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA (Hibernate) Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update